name: Python Package CI/CD (Hybrid Approach)

on:
  push:
    branches:
      - develop
      - release/*
      - hotfix/*
      - main
    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - develop
      - main

  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Choose environment to deploy to'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for setuptools-scm to get full version info

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build setuptools-scm

      - name: Build the package
        run: python -m build

      - name: Get package version
        id: package-version
        run: |
          VERSION=$(python -m setuptools_scm)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Upload version info
        uses: actions/upload-artifact@v3
        with:
          name: version
          path: |
            ${{ steps.package-version.outputs.version }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Install the package and test dependencies
        run: |
          pip install dist/*.whl
          pip install pytest

      - name: Run tests
        run: pytest --cov=sideqr --cov-report=xml tests/

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  deploy-testpypi:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/develop' ||
      startsWith(github.ref, 'refs/heads/release/') ||
      startsWith(github.ref, 'refs/heads/hotfix/') ||
      github.event.inputs.target_environment == 'testpypi'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Twine
        run: pip install --upgrade twine

      - name: Verify package
        run: twine check dist/*

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/* --verbose

  deploy-pypi:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/v') || 
      github.event.inputs.target_environment == 'pypi'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Download version info
        uses: actions/download-artifact@v3
        with:
          name: version
          path: ./version

      - name: Validate version consistency
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PKG_VERSION=$(cat ./version/version)
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "Error: Tag version $TAG_VERSION does not match package version $PKG_VERSION"
            exit 1
          fi

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Twine
        run: pip install --upgrade twine

      - name: Verify package
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/* --verbose